name: cwt-cert
channels:
  - cdat
  - conda-forge
  - defaults
dependencies:
  - esgf-compute-api=2.1.0
  - esgf-compute-cert=devel
  - asn1crypto=0.24.0
  - atomicwrites=1.3.0
  - attrs=18.2.0
  - blas=1.1
  - bzip2=1.0.6
  - ca-certificates=2018.11.29
  - cdat_info=8.1.1
  - cdms2=3.1.2
  - cdtime=3.1.2
  - certifi=2018.11.29
  - cffi=1.12.2
  - chardet=3.0.4
  - cryptography=2.5
  - curl=7.64.0
  - decorator=4.3.2
  - distarray=2.12.2
  - enum34=1.1.6
  - esmf=7.1.0
  - esmpy=7.1.0
  - funcsigs=1.0.2
  - functools32=3.2.3.2
  - future=0.17.1
  - g2clib=1.6.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - idna=2.8
  - ipaddress=1.0.22
  - ipython_genutils=0.2.0
  - jasper=1.900.1
  - jpeg=9c
  - jsonschema=3.0.0
  - jupyter_core=4.4.0
  - krb5=1.16.3
  - libcdms=3.1.2
  - libcf=1.0.2
  - libcurl=7.64.0
  - libdrs=3.1.2
  - libdrs_f=3.1.2
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=7.3.0
  - libgfortran-ng=7.2.0
  - libnetcdf=4.6.2
  - libpng=1.6.36
  - libssh2=1.8.0
  - libstdcxx-ng=7.3.0
  - libtiff=4.0.10
  - more-itertools=4.3.0
  - mpi=1.0
  - mpich=3.2.1
  - nbformat=4.4.0
  - ncurses=6.1
  - netcdf-fortran=4.4.5
  - numpy=1.16.2
  - openblas=0.3.3
  - openssl=1.1.1b
  - ossuuid=1.6.2
  - pathlib2=2.3.3
  - pip=19.0.3
  - pluggy=0.9.0
  - py=1.8.0
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pyrsistent=0.14.11
  - pysocks=1.6.8
  - pytest=4.3.0
  - python=2.7.15
  - pyxb=1.2.6
  - readline=7.0
  - requests=2.21.0
  - scandir=1.9.0
  - setuptools=40.8.0
  - six=1.12.0
  - sqlite=3.26.0
  - tk=8.6.9
  - traitlets=4.3.2
  - urllib3=1.24.1
  - wheel=0.33.1
  - xz=5.2.4
  - zlib=1.2.11
  - nomkl=3.0
  - pip:
    - cwt-certification==0.1.0
    - mv2==3.0.0
    - regrid2==3.0.0
