name: cwt_cert
channels:
  - cdat
  - conda-forge
  - defaults
dependencies:
  - esgf-compute-api=2.1.0
  - asn1crypto=0.24.0
  - atomicwrites=1.2.1
  - attrs=18.2.0
  - blas=1.1
  - ca-certificates=2018.11.29
  - cdat_info=8.0
  - cdms2=3.1.0
  - cdtime=3.1.0
  - certifi=2018.11.29
  - cffi=1.11.5
  - chardet=3.0.4
  - curl=7.49.1
  - distarray=2.12.2
  - enum34=1.1.6
  - esmf=7.1.0r
  - esmpy=7.1.0r
  - funcsigs=1.0.2
  - future=0.17.1
  - g2clib=1.6.0
  - hdf4=4.2.13
  - hdf5=1.10.1
  - idna=2.8
  - ipaddress=1.0.22
  - jasper=1.900.1
  - jpeg=9c
  - libcdms=3.0.1
  - libcf=1.0.2
  - libdrs=3.1.0
  - libdrs_f=3.1.0
  - libgcc=4.8.5
  - libnetcdf=4.6.1
  - libpng=1.6.36
  - libtiff=4.0.10
  - more-itertools=4.3.0
  - mpi=1.0
  - mpich=3.2.1
  - netcdf-fortran=4.4.4
  - numpy=1.16.0
  - openblas=0.3.3
  - openssl=1.1.1a
  - ossuuid=1.6.2
  - pathlib2=2.3.3
  - pluggy=0.8.1
  - py=1.7.0
  - pycparser=2.19
  - pyopenssl=18.0.0
  - pysocks=1.6.8
  - pytest=4.1.1
  - pyxb=1.2.6
  - requests=2.21.0
  - scandir=1.9.0
  - six=1.12.0
  - urllib3=1.24.1
  - xz=5.2.4
  - cryptography=2.4.2
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libgfortran-ng=3.0.1
  - ncurses=6.1
  - nomkl=3.0
  - pip=18.1
  - python=2.7.15
  - readline=7.0
  - setuptools=40.6.3
  - sqlite=3.26.0
  - tk=8.6.8
  - wheel=0.32.3
  - zlib=1.2.11
