{% set data = load_setup_py_data() %}

package:
  name: esgf-compute-cert
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python
  number: {{ environ.get('BUILD_NUMBER', 0) }}

requirements:
  build:
    - git

  host:
    - python

  run:
    - python=3.7.0
    - pytest=4.5.0
    - nomkl=3.0
    - cdms2=3.1.2
    - libnetcdf=4.6.2
    - esgf-compute-api={{ environ.get('COMPUTE_API_VER') }}
    - jsonschema=3.0.1

test:
  imports:
    - cwt_cert
    - cwt_cert.conftest
    - cwt_cert.test_server
    - cwt_cert.test_operator

  commands:
    - cwt-cert -h

about:
  home: https://github.com/ESGF/esgf-compute-cert
  summary: tool to certify ESGF compute servers
