package:
  name: esgf-compute-cert
  version: {{ environ.get('PACKAGE_VERSION', 'devel') }}

source:
  git_rev: {{ environ.get('GIT_BRANCH', 'devel') }}
  git_url: ../

build:
  string: py{{ PY_VER }}_{{ GIT_FULL_HASH|truncate(8, False, '') }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - git

  host:
    - python

  run:
    - python
    - pytest
    - nomkl
    - cdms2>=3.1.0
    - esgf-compute-api=2.1.0
    - jsonschema

about:
  home: https://github.com/ESGF/esgf-compute-cert
  summary: tool to certify ESGF compute servers
