package:
  name: esgf-compute-cert
  version: {{ environ.get('PACKAGE_VERSION', 'devel') }}

source:
  path: ../

build:
  number: {{ environ.get('BUILD_NUMBER', 0) }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  build:
    - git

  host:
    - python

  run:
    - python
    - pytest
    - nomkl
    - cdms2>=3.1.0
    - esgf-compute-api=devel
    - jsonschema

test:
  commands:
    - cwt-cert -h

about:
  home: https://github.com/ESGF/esgf-compute-cert
  summary: tool to certify ESGF compute servers
